# Labels for PRs based on changed files
electron-app:
  - electron-calculator/**

android-app:
  - android-apk/**

documentation:
  - '*.md'
  - docs/**

ci-cd:
  - .github/**

calculator-module:
  - electron-calculator/app.js

ui-ux:
  - electron-calculator/index.html
  - electron-calculator/src/styles/**

tutorial:
  - electron-calculator/app.js

i18n:
  - electron-calculator/app.js
